stages:
  - build
  - test

build-arm:
  image: spacedot/build-arm
  stage: build
  script:
    - mkdir conan-build
    - conan profile detect --force
    - cp conan-arm-profile /root/.conan2/profiles/
    - conan remote add conan https://artifactory.spacedot.gr/artifactory/api/conan/conan
    - conan remote login -p $CONAN_PASSWORD conan $CONAN_USER
    - cd lib
    - git clone https://gitlab.com/acubesat/obc/cross-platform-software.git
    - git clone https://gitlab.com/acubesat/obc/atsam-component-drivers.git
    - cd cross-platform-software && git submodule update --init --recursive 
    - cd ..
    - cd .. 
    - conan install . --output-folder conan-build --build=missing -pr conan-arm-profile
    - cmake . -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=conan-build/build/Debug/generators/conan_toolchain.cmake -DCMAKE_CXX_COMPILER="arm-none-eabi-g++" -DCMAKE_C_COMPILER="arm-none-eabi-gcc"
    - make -j$(nproc)
  artifacts:
    when: always
    paths:
      - OBC_SOFTWARE.elf

test-hw:
  image: spacedot/build-arm
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    GIT_SUBMODULE_STRATEGY: normal
    TERM: xterm-color
    CLICOLOR_FORCE: 1 # Necessary for cmake to output colours
    PYTHONIOENCODING: utf-8

  # Global caching directive for pip
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - .cache/pip

  before_script:
    - apt-get update && apt-get install --yes --no-install-recommends wget binutils cmake make python3 python3-pip
    - pip3 install pyserial==3.5 pyusb pyocd==0.36.0 pytest --break-system-packages
    - git clone https://gitlab.com/acubesat/obc/hil-tests --branch atsamv71q21-debug
    - cd hil-tests
    - wget https://packs.download.microchip.com/Microchip.SAMV71_DFP.4.5.82.pack

  script:
    - python3 -c "import serial; print(serial.VERSION)"
    - python3 test.py -b ../OBC_SOFTWARE.elf -s /dev/ttyACM0 -i AT -r 115200
