#include "ECSS_Configuration.hpp"

#ifdef SERVICE_PARAMETER

#include "Services/ParameterService.hpp"
#include "PlatformParameters.hpp"

void ParameterService::initializeParameterMap() {
    parameters = {{PlatformParameters::OnBoardYear,                 PlatformParameters::onBoardYear},
                  {PlatformParameters::OnBoardMonth,                PlatformParameters::onBoardMonth},
                  {PlatformParameters::OnBoardDay,                  PlatformParameters::onBoardDay},
                  {PlatformParameters::OnBoardHour,                 PlatformParameters::onBoardHour},
                  {PlatformParameters::OnBoardMinute,               PlatformParameters::onBoardMinute},
                  {PlatformParameters::OnBoardSecond,               PlatformParameters::onBoardSecond},
                  {PlatformParameters::ReportParametersUnusedStack, PlatformParameters::reportParametersUnusedStack},
                  {PlatformParameters::AvailableHeap,               PlatformParameters::availableHeap},
                  {PlatformParameters::OBCBoardTemperature1,        PlatformParameters::obcBoardTemperature1},
                  {PlatformParameters::OBCBootCounter,              PlatformParameters::obcBootCounter},
                  {PlatformParameters::OBCSystick,                  PlatformParameters::obcSysTick},
                  {PlatformParameters::OBCMCUTemperature,           PlatformParameters::mcuTemperature},
                  {PlatformParameters::UseRTT,                      PlatformParameters::useRTT},
                  {PlatformParameters::UseUART,                     PlatformParameters::useUART},
                  {PlatformParameters::UseCAN,                      PlatformParameters::useCAN},
                  {PlatformParameters::SUMCUBootCounter,                  PlatformParameters::SUMCUBootCounter},
                  {PlatformParameters::SUMCUSysTick,                      PlatformParameters::SUMCUSysTick},
                  {PlatformParameters::SUMCUTemperature,                  PlatformParameters::SUMCUTemperature},
                  {PlatformParameters::SUMCUInputVoltage,                 PlatformParameters::SUMCUInputVoltage},
                  {PlatformParameters::FlashIntUsedPercentage,          PlatformParameters::flashIntUsedPercentage},
                  {PlatformParameters::FlashUsedPercentage,             PlatformParameters::flashUsedPercentage},
                  {PlatformParameters::SRAMUsedPercentage,              PlatformParameters::sramUsedPercentage},
                  {PlatformParameters::NANDCurrentlyUsedPartition,      PlatformParameters::nandCurrentlyUsedPartition},
                  {PlatformParameters::NANDFlashLCLOn,                  PlatformParameters::nandFlashLclOn},
                  {PlatformParameters::NANDFlashLCLThreshold,           PlatformParameters::nandFlashLclThreshold},
                  {PlatformParameters::NANDFlashScrubbingFrequency,     PlatformParameters::nandFlashScrubbingFrequency},
                  {PlatformParameters::RAMScrubbingFrequency,           PlatformParameters::ramScrubbingFrequency},
                  {PlatformParameters::ProgramFlashScrubbingFrequency,  PlatformParameters::programFlashScrubbingFrequency},
                  {PlatformParameters::ControlPumpFlashLCLOn,           PlatformParameters::controlPumpFlashLclOn},
                  {PlatformParameters::ControlPumpFlashLCLThreshold,    PlatformParameters::controlPumpFlashLclThreshold},
                  {PlatformParameters::FlowPumpFlashOn,                 PlatformParameters::flowPumpFlashOn},
                  {PlatformParameters::FlowPumpFlashLCLThreshold,       PlatformParameters::flowPumpFlashLclThreshold},
                  {PlatformParameters::CameraON,                        PlatformParameters::cameraOn},
                  {PlatformParameters::CameraLCLThreshold,              PlatformParameters::cameraLclThreshold},
                  {PlatformParameters::PCBTemperature1,                 PlatformParameters::pcbTemperature1},
                  {PlatformParameters::PCBTemperature2,                 PlatformParameters::pcbTemperature2},
                  {PlatformParameters::PCBTemperatureControlValves,     PlatformParameters::pcbTemperatureControlValves},
                  {PlatformParameters::PCBTemperatureFlowValves,        PlatformParameters::pcbTemperatureFlowValves},
                  {PlatformParameters::CameraTemperature,               PlatformParameters::cameraTemperature},
                  {PlatformParameters::PDMSTemperature,                 PlatformParameters::pdmsTemperature},
                  {PlatformParameters::GrowthMediumTemperature,         PlatformParameters::growthMediumTemperature},
                  {PlatformParameters::LastFailedEvent,                 PlatformParameters::lastFailedEvent},
                  {PlatformParameters::PressureLevelSensor1,            PlatformParameters::pressureLevelSensor1},
                  {PlatformParameters::PressureLevelSensor2,            PlatformParameters::pressureLevelSensor2},
                  {PlatformParameters::HumidityLevelSensor1,            PlatformParameters::humidityLevelSensor1},
                  {PlatformParameters::HumidityLevelSensor2,            PlatformParameters::humidityLevelSensor2},
                  {PlatformParameters::RADFET,                          PlatformParameters::radfet},
                  {PlatformParameters::PumpFlowRate1,                   PlatformParameters::pumpFlowRate1},
                  {PlatformParameters::PumpFlowRate2,                   PlatformParameters::pumpFlowRate2},
                  {PlatformParameters::ControlChamberValve1,            PlatformParameters::controlChamberValve1},
                  {PlatformParameters::ControlChamberValve2,            PlatformParameters::controlChamberValve2},
                  {PlatformParameters::ControlChamberValve3,            PlatformParameters::controlChamberValve3},
                  {PlatformParameters::ControlSandwitchValve1,          PlatformParameters::controlSandwitchValve1},
                  {PlatformParameters::ControlSandwitchValve2,          PlatformParameters::controlSandwitchValve2},
                  {PlatformParameters::ControlSandwitchValve3,          PlatformParameters::controlSandwitchValve3},
                  {PlatformParameters::FlowValveInlet1,                 PlatformParameters::flowValveInlet1},
                  {PlatformParameters::FlowValveInlet2,                 PlatformParameters::flowValveInlet2},
                  {PlatformParameters::FlowValveInlet3,                 PlatformParameters::flowValveInlet3},
                  {PlatformParameters::FlowValveOutlet1,                PlatformParameters::flowValveOutlet1},
                  {PlatformParameters::FlowValveOutlet2,                PlatformParameters::flowValveOutlet2},
                  {PlatformParameters::FlowValveOutlet3,                PlatformParameters::flowValveOutlet3},
                  {PlatformParameters::FlowValveTest1,                  PlatformParameters::flowValveTest1},
                  {PlatformParameters::FlowValveTest2,                  PlatformParameters::flowValveTest2},
                  {PlatformParameters::LEDIntensity1,                   PlatformParameters::ledIntensity1},
                  {PlatformParameters::LEDIntensity2,                   PlatformParameters::ledIntensity2},
                  {PlatformParameters::LEDIntensity3,                   PlatformParameters::ledIntensity3},
                  {PlatformParameters::LEDIntensity4,                   PlatformParameters::ledIntensity4},
                  {PlatformParameters::NumberOfPhotosTaken,             PlatformParameters::numberOfPhotosTaken},
                  {PlatformParameters::PhotoExposureTime,               PlatformParameters::photoExposureTime},
                  {PlatformParameters::PhotoInterval,                   PlatformParameters::photoInterval},
                  {PlatformParameters::PhotoCroppedResolution,          PlatformParameters::photoCroppedResolution},
                  {PlatformParameters::PhotoCompressionRate,            PlatformParameters::photoCompressionRate},
                  {PlatformParameters::PhotoCompressionRate,            PlatformParameters::experimentNumber},
                  {PlatformParameters::OnBoardTime,                     PlatformParameters::onBoardTime}};
}

#endif
